// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC5yCriZxyngzIGrdNt3mEVGI-lshCP1M',
    appId: '1:190177585008:web:68a71d6cf169e9b6bc11b5',
    messagingSenderId: '190177585008',
    projectId: 'frandchat',
    authDomain: 'frandchat.firebaseapp.com',
    storageBucket: 'frandchat.appspot.com',
    measurementId: 'G-B2DMX9YMDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcadh2gy6leBqje-GIl0OE5Wcvkmlxgfk',
    appId: '1:190177585008:android:f1e4335521084c0cbc11b5',
    messagingSenderId: '190177585008',
    projectId: 'frandchat',
    storageBucket: 'frandchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdFRO7D3Au4HR_QChA8s9e6KUMzacq7r0',
    appId: '1:190177585008:ios:e1f5ba7a3311221ebc11b5',
    messagingSenderId: '190177585008',
    projectId: 'frandchat',
    storageBucket: 'frandchat.appspot.com',
    iosClientId: '190177585008-rir69uhrbdk4qptg5a7it71r0itfoloh.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdFRO7D3Au4HR_QChA8s9e6KUMzacq7r0',
    appId: '1:190177585008:ios:e1f5ba7a3311221ebc11b5',
    messagingSenderId: '190177585008',
    projectId: 'frandchat',
    storageBucket: 'frandchat.appspot.com',
    iosClientId: '190177585008-rir69uhrbdk4qptg5a7it71r0itfoloh.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendchat',
  );
}
